cask 'font-microsoft-aptos' do
    name 'Microsoft Aptos'
    version '4.40'
    sha256 '6528fd120e719a9f985e94214eca6887d1653b88456916a792a630b02e95b025'
  
    url 'https://download.microsoft.com/download/8/6/0/860a94fa-7feb-44ef-ac79-c072d9113d69/Microsoft%20Aptos%20Fonts.zip'
    homepage 'https://www.microsoft.com/en-us/download/details.aspx?id=106087'
  
    font 'Aptos-Black-Italic.ttf'
    font 'Aptos-Black.ttf'
    font 'Aptos-Bold-Italic.ttf'
    font 'Aptos-Bold.ttf'
    font 'Aptos-Display-Bold-Italic.ttf'
    font 'Aptos-Display-Bold.ttf'
    font 'Aptos-Display-Italic.ttf'
    font 'Aptos-Display.ttf'
    font 'Aptos-ExtraBold-Italic.ttf'
    font 'Aptos-ExtraBold.ttf'
    font 'Aptos-Italic.ttf'
    font 'Aptos-Light-Italic.ttf'
    font 'Aptos-Light.ttf'
    font 'Aptos-Mono-Bold-Italic.ttf'
    font 'Aptos-Mono-Bold.ttf'
    font 'Aptos-Mono-Italic.ttf'
    font 'Aptos-Mono.ttf'
    font 'Aptos-Narrow-Bold-Italic.ttf'
    font 'Aptos-Narrow-Bold.ttf'
    font 'Aptos-Narrow-Italic.ttf'
    font 'Aptos-Narrow.ttf'
    font 'Aptos-SemiBold-Italic.ttf'
    font 'Aptos-SemiBold.ttf'
    font 'Aptos-Serif-Bold-Italic.ttf'
    font 'Aptos-Serif-Bold.ttf'
    font 'Aptos-Serif-Italic.ttf'
    font 'Aptos-Serif.ttf'
    font 'Aptos.ttf'
  end
  